version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 5000:4002
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: postgres:13
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis_volume:/var/lib/redis
    env_file:
      - .env
volumes:
  postgres:
  redis_volume: